Feature/get all poets
WebConsul/poetry-laravel-api pull request #12
Opened 2022-09-28 08:02 UTC by dku1

2022-09-28 11:37 UTC, poymanov commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
Я бы вынес число 20 в конфиг. Вдруг когда-то захочется поменять это значение? Да и кроме этого, какое-то "магическое" число получается - https://ru.hexlet.io/blog/posts/magic-numbers

2022-09-29 11:14 UTC, dku1 commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
Мне кажется хорошая идея. Я мог бы сделать. Или стоит отдельным таском сделать?

2022-09-29 11:18 UTC, poymanov commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
Можно прямо здесь.

Нужно создать в `/config` создать какой-нибудь файл, типа `pagination.php` и в него подобные значения вносить через `env()`. А в контроллере можно либо вызывать `config(pagination.xxxx)` где нужно, либо внедрять через **Dependency Injection** и тоже вызывать где нужно.

2022-09-29 11:50 UTC, dku1 commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
Сделал. Может стоило в .env тоже константу добавить сразу?

2022-09-29 11:52 UTC, poymanov commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
Да, надо добавить в `env`. Чтобы можно было быстро поменять это.

Плюс по названию: у нас может быть много ресурсов, для которых понадобится хранить количество элементов на странице. Мы либо решаем, что вообще для всех них будет одинаковое значение, либо заводим для каждого отдельное значение в конфиге и `env`.

2022-09-29 12:00 UTC, dku1 commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
А в конфиге по дефолту ставить что-то?

2022-09-29 12:05 UTC, poymanov commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
Можно не ставить. Пусть лучше в `env` будет какое-то значение. Оно должно там быть, если его нет, считай что ошибка.

2022-09-29 12:15 UTC, dku1 commented on app/Http/Controllers/PoetController.php
> +        $perPage = $request->input('per_page') ?? 20;
Готово.

2022-09-30 08:25 UTC, ekut requested changes
Отлично сделано с конфигурацией!
Но я вредничаю и прошу добавить ещё один штришок.

2022-09-30 08:25 UTC, ekut commented on app/Http/Controllers/PoetController.php
> +    public function get_poets(Request $request): JsonResponse
PSR-1 заставляет нас назвать этот метод `getPoets` (camelCase)

2022-09-30 08:25 UTC, ekut commented on routes/api.php
> +Route::get('/poets', [PoetController::class, 'get_poets']);
Соответственно, нужно изменить название метода тоже

2022-09-30 08:25 UTC, ekut commented on app/Http/Controllers/PoetController.php
> +    public function get_poets(Request $request): JsonResponse
И ещё один, последний штришок. Можешь сделать валидацию реквеста с помощью FormRequest (https://laravel.com/docs/9.x/validation#form-request-validation)?
Это вроде бы, не имеет большого смысла, но нам нужно сделать такую "схему", по которой будут делаться все остальные эндпойнты, в том числе и со сложной структурой реквестов, где без валидации не обойтись. Твой эндпойнт будет эталоном, примером и идеалом :)

2022-09-30 14:54 UTC, dku1 commented on app/Http/Controllers/PoetController.php
> +    public function get_poets(Request $request): JsonResponse
Понял, сейчас займусь!

2022-10-01 05:29 UTC, dku1 commented on app/Http/Controllers/PoetController.php
> +    public function get_poets(Request $request): JsonResponse
Я сделал, но уверен, что есть недочёты.

2022-10-02 06:12 UTC, ekut approved these changes
Отлично! Я ещё немножко изменений внёс. Давай в таком виде и вмёржим, и дальше будем развивать.

2022-10-02 06:13 UTC, ekut commented on app/Http/Controllers/PoetController.php
> +    public function get_poets(Request $request): JsonResponse
Недочётов нет, как нет и пределов совершенству. Поэтому любой код можно изменять до бесконечности. Главное - вовремя остановиться и вмёржить в девелоп :)

2022-10-02 06:14 UTC, merged

2022-10-02 08:09 UTC, dku1 commented on app/Http/Controllers/PoetController.php
> +    public function get_poets(Request $request): JsonResponse
Окей, вынес тонну опыта лишь с одного таска) Спасибо!