Feature/create tests swagger
WebConsul/poetry-laravel-api pull request #14
Opened 2022-09-30 14:57 UTC by z-takaev

2022-10-01 01:28 UTC, ekut requested changes
В целом всё отлично, спасибо!
Но есть два важных момента. 
1. Комментарии в коде пишем на английском языке.
2. composer.lock не должен обновляться в таких пулл-реквестах. То есть, не нужно делать `composer upgrade` или что-то подобное. Я подробнее опишу в общем чате. А пока нужно откатить это изменение

2022-10-01 01:28 UTC, ekut commented on tests/Feature/SwaggerTest.php
> +     * Страница с документацией возвращает успешный ответ
Комментарии в коде должны быть на английском языке. Я бы сказал, что здесь они даже излишни, потому что имя метода содержит всю необходимую информацию. Но если уж комментарий сделан, он должен быть на английском. Сюда вполне могут прийти нерусскоязычные пользователи/разработчики, или работодатели.

2022-10-01 10:35 UTC, z-takaev commented on tests/Feature/SwaggerTest.php
> +     * Страница с документацией возвращает успешный ответ
Комментарий на русском увидел в другом месте и решил что так и нужно) с composer.lock накосячил сильно(не знал), я запускал composer update. Исправлю!

2022-10-02 04:35 UTC, ekut approved these changes
Отлично! Спасибо

2022-10-02 04:36 UTC, merged